[settings]
;debug=Y
title=NEED FOR MADNESS 2 (Prototype for Revised And Recharged)
;titleimage=mainmenu.gif
numselections=1
defaultselection=1

selscreenfull1=n
Seldesc1=Play Fullscreen
selscreensize1=800,480
selgamesize1=800,480
selcode1=runexit
selurl1=Game.html
selquality1=high
selscreencolordepth1=32
selinf1=ATXPWJLA
selscreenbgcolor1=000000
Selgamebgcolor1=000000
selscreenclosebtn1=y
Selcloseonevent1=Y
